/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import javax.swing.JButton;
import javax.swing.JList;

/**
 *
 * @author esber
 */
public class Admin_Menu extends javax.swing.JFrame implements implemenable {

    /**
     * Creates new form GuiAdmin
     */
    public Admin_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        crudPetugas = new javax.swing.JButton();
        crudPemilih = new javax.swing.JButton();
        crudKandidat = new javax.swing.JButton();
        crudTPS = new javax.swing.JButton();
        inputPetugasTps = new javax.swing.JButton();
        inputPemilihTps = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setForeground(new java.awt.Color(253, 251, 251));
        jPanel1.setToolTipText("");
        jPanel1.setPreferredSize(new java.awt.Dimension(729, 443));
        jPanel1.setRequestFocusEnabled(false);

        btnHome.setBackground(new java.awt.Color(0, 0, 0));
        btnHome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setText("Back");

        crudPetugas.setBackground(new java.awt.Color(51, 51, 51));
        crudPetugas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        crudPetugas.setForeground(new java.awt.Color(255, 255, 255));
        crudPetugas.setText("CRUD Petugas");
        crudPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crudPetugasActionPerformed(evt);
            }
        });

        crudPemilih.setBackground(new java.awt.Color(51, 51, 51));
        crudPemilih.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        crudPemilih.setForeground(new java.awt.Color(255, 255, 255));
        crudPemilih.setText("CRUD Pemilih");

        crudKandidat.setBackground(new java.awt.Color(51, 51, 51));
        crudKandidat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        crudKandidat.setForeground(new java.awt.Color(255, 255, 255));
        crudKandidat.setText("CRUD Kandidat");
        crudKandidat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crudKandidatActionPerformed(evt);
            }
        });

        crudTPS.setBackground(new java.awt.Color(51, 51, 51));
        crudTPS.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        crudTPS.setForeground(new java.awt.Color(255, 255, 255));
        crudTPS.setText("CRUD TPS");

        inputPetugasTps.setBackground(new java.awt.Color(51, 51, 51));
        inputPetugasTps.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        inputPetugasTps.setForeground(new java.awt.Color(255, 255, 255));
        inputPetugasTps.setText("Input Petugas di TPS");

        inputPemilihTps.setBackground(new java.awt.Color(51, 51, 51));
        inputPemilihTps.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        inputPemilihTps.setForeground(new java.awt.Color(255, 255, 255));
        inputPemilihTps.setText("Input Pemilih Ke TPS");

        jPanel2.setBackground(new java.awt.Color(102, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENU ADMIN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inputPetugasTps)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(crudPetugas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(crudPemilih, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(crudKandidat, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(crudTPS, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(inputPemilihTps))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crudPemilih, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crudKandidat, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crudTPS, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crudPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputPetugasTps, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputPemilihTps, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(btnHome)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crudPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crudPetugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crudPetugasActionPerformed

    private void crudKandidatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crudKandidatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crudKandidatActionPerformed

    /**
     * @param args the command line arguments
     */
    
     //Button
    public JButton getCrudPetugas() {
        return crudPetugas;
    }

    public JButton getCrudPemilih() {
        return crudPemilih;
    }
    
    public JButton getCrudKandidat() {
        return crudKandidat;
    }

    public JButton getCrudTps() {
        return crudTPS;
    }
    
    public JButton getPetugasTPS() {
        return inputPetugasTps;
    }

    public JButton getPemilihTps() {
        return inputPemilihTps;
    }
     
    public JButton getBtnHome() {
        return btnHome;
    }
    //Listener
    public void Listener(ActionListener A)
    {
        crudPetugas.addActionListener(A);
        crudPemilih.addActionListener(A);
        crudKandidat.addActionListener(A);
        crudTPS.addActionListener(A);
        inputPetugasTps.addActionListener(A);
        inputPemilihTps.addActionListener(A);
        btnHome.addActionListener(A);
    }
    
  

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton crudKandidat;
    private javax.swing.JButton crudPemilih;
    private javax.swing.JButton crudPetugas;
    private javax.swing.JButton crudTPS;
    private javax.swing.JButton inputPemilihTps;
    private javax.swing.JButton inputPetugasTps;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void Adapter(MouseAdapter e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void ResetView() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
