/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import javax.swing.JButton;
import javax.swing.JList;

/**
 *
 * @author esber
 */
public class CRUD_Petugas extends javax.swing.JFrame implements implemenable {

    /**
     * Creates new form GuiAdmin
     */
    public CRUD_Petugas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        tfNIK = new javax.swing.JTextField();
        tfID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListPetugas = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txPetugas = new javax.swing.JTextArea();
        deletePetugas = new javax.swing.JButton();
        editPetugas = new javax.swing.JButton();
        addPetugas = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setForeground(new java.awt.Color(253, 251, 251));
        jPanel1.setToolTipText("");
        jPanel1.setPreferredSize(new java.awt.Dimension(729, 443));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(1, 1, 1));
        jLabel2.setText("Tambah Petugas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 89, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(1, 1, 1));
        jLabel3.setText("Nama Petugas");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 136, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(1, 1, 1));
        jLabel4.setText("NIK");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 179, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(1, 1, 1));
        jLabel5.setText("ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 225, -1, -1));

        tfNama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaActionPerformed(evt);
            }
        });
        jPanel1.add(tfNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 133, 157, -1));

        tfNIK.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(tfNIK, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 179, 157, -1));

        tfID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(tfID, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 225, 157, -1));

        jLabel6.setFont(new java.awt.Font("Noto Sans", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(1, 1, 1));
        jLabel6.setText("Data Petugas");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 89, -1, -1));

        ListPetugas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(ListPetugas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 133, 93, 160));

        txPetugas.setColumns(20);
        txPetugas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txPetugas.setRows(5);
        jScrollPane2.setViewportView(txPetugas);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 136, 176, 160));

        deletePetugas.setBackground(new java.awt.Color(1, 1, 1));
        deletePetugas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deletePetugas.setForeground(new java.awt.Color(254, 254, 254));
        deletePetugas.setText("Delete");
        jPanel1.add(deletePetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, -1, -1));

        editPetugas.setBackground(new java.awt.Color(1, 1, 1));
        editPetugas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        editPetugas.setForeground(new java.awt.Color(254, 254, 254));
        editPetugas.setText("Edit");
        editPetugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editPetugasMouseClicked(evt);
            }
        });
        jPanel1.add(editPetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 67, -1));

        addPetugas.setBackground(new java.awt.Color(1, 1, 1));
        addPetugas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addPetugas.setForeground(new java.awt.Color(254, 254, 254));
        addPetugas.setText("Add");
        jPanel1.add(addPetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 67, -1));

        btnMenu.setBackground(new java.awt.Color(1, 1, 1));
        btnMenu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(254, 254, 254));
        btnMenu.setText("Back");
        btnMenu.setRequestFocusEnabled(false);
        jPanel1.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 403, 70, 30));

        jPanel2.setBackground(new java.awt.Color(102, 0, 0));

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CRUD Petugas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 725, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaActionPerformed

    private void editPetugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editPetugasMouseClicked
        
    }//GEN-LAST:event_editPetugasMouseClicked

    /**
     * @param args the command line arguments
     */

    //Get Data
    public String getTFNama()
    {
        return tfNama.getText();
    }
    
    public String getTFNik()
    {
        return tfNIK.getText();
    }
    
    public String getTFID()
    {
        return tfID.getText();
    }
    
    //Listener and Adapter
    public void Listener(ActionListener AL)
    {
        addPetugas.addActionListener(AL);
        deletePetugas.addActionListener(AL);
        editPetugas.addActionListener(AL);
        btnMenu.addActionListener(AL);
    }
    
    public void Adapter(MouseAdapter ME)
    {
        ListPetugas.addMouseListener(ME);
    }
    
    //Reset Tampilan
    public void ResetView()
    {
        tfNama.setText("");
        tfNIK.setText("");
        tfID.setText("");
        ListPetugas.clearSelection();
        ListPetugas.clearSelection();
        txPetugas.setText("");
    }
    
    //LIST DATA PANITIA
    public void setListPetugas(String data[])
    {
        ListPetugas.setListData(data);
    }
    
    public JList getListPetugas() 
    {
        return ListPetugas;
    }
    
    public void setTextPetugas(String data)
    {
        txPetugas.setText(data);
    }
    
    public String getSelectedPetugas()
    {
        return ListPetugas.getSelectedValue();
    }
    
    //Get Button
    
    public JButton getAddPetugas() {
        return addPetugas;
    }

    public JButton getDeletePetugas() {
        return deletePetugas;
    }

    public JButton getEditPetugas() {
        return editPetugas;
    }

    public JButton getBtnMenu() {
        return btnMenu;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListPetugas;
    private javax.swing.JButton addPetugas;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton deletePetugas;
    private javax.swing.JButton editPetugas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfNIK;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextArea txPetugas;
    // End of variables declaration//GEN-END:variables
}
