/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author esber
 */
public class HOME extends javax.swing.JFrame {

    /**
     * Creates new form HOME
     */
    public HOME() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        asAdmin = new javax.swing.JButton();
        asPetugas = new javax.swing.JButton();
        asPemilih = new javax.swing.JButton();
        asKandidat = new javax.swing.JButton();
        asAlluser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(729, 443));

        jLabel2.setFont(new java.awt.Font("Jamrul", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(1, 1, 1));
        jLabel2.setText("APLIKASI PEMILU");

        jLabel3.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(1, 1, 1));
        jLabel3.setText("Silahkan Pilih Menu :");

        asAdmin.setBackground(new java.awt.Color(255, 255, 255));
        asAdmin.setForeground(new java.awt.Color(253, 251, 251));
        asAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/button.png"))); // NOI18N
        asAdmin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        asPetugas.setBackground(new java.awt.Color(255, 255, 255));
        asPetugas.setForeground(new java.awt.Color(253, 251, 251));
        asPetugas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/buttonpetugas.png"))); // NOI18N
        asPetugas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        asPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asPetugasActionPerformed(evt);
            }
        });

        asPemilih.setBackground(new java.awt.Color(255, 255, 255));
        asPemilih.setForeground(new java.awt.Color(253, 251, 251));
        asPemilih.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/buttonpemlih.png"))); // NOI18N
        asPemilih.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        asPemilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asPemilihActionPerformed(evt);
            }
        });

        asKandidat.setBackground(new java.awt.Color(255, 255, 255));
        asKandidat.setForeground(new java.awt.Color(253, 251, 251));
        asKandidat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/button kandidat.png"))); // NOI18N
        asKandidat.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        asAlluser.setBackground(new java.awt.Color(255, 255, 255));
        asAlluser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        asAlluser.setForeground(new java.awt.Color(253, 251, 251));
        asAlluser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/buttonuser.png"))); // NOI18N
        asAlluser.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        asAlluser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asAlluserActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/logo Pemilu.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 280, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(asKandidat)
                                    .addComponent(asAdmin)
                                    .addComponent(asPetugas))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(asAlluser)
                                    .addComponent(asPemilih)))
                            .addComponent(jLabel2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(asAdmin))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(asAlluser)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(asPetugas)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(asKandidat)
                            .addComponent(asPemilih))))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void asPemilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asPemilihActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asPemilihActionPerformed

    private void asPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asPetugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asPetugasActionPerformed

    private void asAlluserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asAlluserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asAlluserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HOME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton asAdmin;
    private javax.swing.JButton asAlluser;
    private javax.swing.JButton asKandidat;
    private javax.swing.JButton asPemilih;
    private javax.swing.JButton asPetugas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
    //GET BUTTON
    public JButton getAsAdmin() {
        return asAdmin;
    }

    public JButton getAsPetugas() {
        return asPetugas;
    }

    public JButton getAsPemilih() {
        return asPemilih;
    }
    
    public JButton getAsKandidat() {
        return asKandidat;
    }


    public void Listener(ActionListener e)
    {
        asAdmin.addActionListener(e);
        asPetugas.addActionListener(e);
        asPemilih.addActionListener(e);
        asKandidat.addActionListener(e);
        asAlluser.addActionListener(e);
    }
}
