/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Aldy
 */
import Controller.Controller_Input_Pemilih;
import Model.*;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;
public class Petugas_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Petugas_Menu
     */
    DefaultTableModel model;
    String pilihan,pemilih= null;
    Application app;
    Petugas petugas = null;
    
    public Petugas_Menu(Petugas p) {
        initComponents();
        app = new Application();
        petugas = p;
        String [] judul = {"Pemilih","NIK","Pilihan","No Urut"};
        model = new DefaultTableModel(judul,0);
        tabelVerifikasi.setModel(model);
        app.loadPemilih();
        app.loadKandidat();
        app.loadPetugas();
        TampilTabel(petugas);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelVerifikasi = new javax.swing.JTable();
        btnVerifikasi = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(729, 443));

        tabelVerifikasi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabelVerifikasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Pemilih", "NIK", "Pilihan", "No.Urut"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelVerifikasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelVerifikasiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelVerifikasi);
        if (tabelVerifikasi.getColumnModel().getColumnCount() > 0) {
            tabelVerifikasi.getColumnModel().getColumn(0).setResizable(false);
            tabelVerifikasi.getColumnModel().getColumn(1).setResizable(false);
            tabelVerifikasi.getColumnModel().getColumn(2).setResizable(false);
            tabelVerifikasi.getColumnModel().getColumn(3).setResizable(false);
        }

        btnVerifikasi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVerifikasi.setText("Verifikasi");

        btnMenu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMenu.setText("Back");

        jPanel2.setBackground(new java.awt.Color(102, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VERIFIKASI PEMILIHAN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel1)
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(30, 30, 30))
        );

        jTextField1.setText("TPS Petugas : ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVerifikasi))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerifikasi)
                    .addComponent(btnMenu))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelVerifikasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelVerifikasiMouseClicked
        // TODO add your handling code here:
        int i = tabelVerifikasi.getSelectedRow();
        if(i>=0){
            this.pilihan = model.getValueAt(i,3).toString();
            this.pemilih = model.getValueAt(i,1).toString();
        }
    }//GEN-LAST:event_tabelVerifikasiMouseClicked
    public void TampilTabel(Petugas p){
        Petugas pt = p;
        int row = tabelVerifikasi.getRowCount();
        for (int a = 0; a < row; a++) {
           model.removeRow(0);
        }
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_pemilu","root","");
            ResultSet rs = cn.createStatement().executeQuery("SELECT * from Pemilihan ");
            while(rs.next()){
                String data[]= {
                    app.getPemilih(rs.getString(1)).getNama(),app.getPemilih(rs.getString(1)).getNIK(),
                    app.getKandidatbyNoUrut(rs.getString(2)).getNama(),rs.getString(2)
                };
                model.addRow(data);
            }
        }catch (SQLException ex) {
            Logger.getLogger(Input_Petugas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void Listener(ActionListener A)
    {
        btnMenu.addActionListener(A);
        btnVerifikasi.addActionListener(A);
    }
    
    public JButton getBack(){
        return btnMenu;
    }
    
    public JButton getVerifikasi(){
        return btnVerifikasi;
    }
    
    public String getSelectedPilihan(){
        return pilihan;
    }
    
    public String getSelectedPemilih(){
        return pemilih;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnVerifikasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tabelVerifikasi;
    // End of variables declaration//GEN-END:variables
}
